// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6DBeQNaknLWsdXl2sVXF0g5_hzkqauN8',
    appId: '1:601963106041:web:a9fc6f7866b1fe06e95c28',
    messagingSenderId: '601963106041',
    projectId: 'finx-e436a',
    authDomain: 'finx-e436a.firebaseapp.com',
    storageBucket: 'finx-e436a.appspot.com',
    measurementId: 'G-2MN9ZBJF29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEs4Em6MEq6XzX78FUFA2xdt9glQ8jpwc',
    appId: '1:601963106041:android:bfdb3d1f31c0d31fe95c28',
    messagingSenderId: '601963106041',
    projectId: 'finx-e436a',
    storageBucket: 'finx-e436a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbIkx4oE5N3b1t2-VRi_5kAj3Uy3qv10Y',
    appId: '1:601963106041:ios:a794450260a2bd5fe95c28',
    messagingSenderId: '601963106041',
    projectId: 'finx-e436a',
    storageBucket: 'finx-e436a.appspot.com',
    iosBundleId: 'com.example.finQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbIkx4oE5N3b1t2-VRi_5kAj3Uy3qv10Y',
    appId: '1:601963106041:ios:471c5a966e365217e95c28',
    messagingSenderId: '601963106041',
    projectId: 'finx-e436a',
    storageBucket: 'finx-e436a.appspot.com',
    iosBundleId: 'com.example.finQuest.RunnerTests',
  );
}
